substitutions:
  name: sonoff-s31

esphome:
  name: sonoff-s31
  friendly_name: Sonoff S31
  comment: Sonoff S31 Wifi Switch

  project:
    name: "Industrial.Sonoff.S31"
    version: "1.0.0"

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

api:

ota:

web_server:
  port: 80

wifi:
  ap:
    ssid: "Sonoff-S31 Hotspot"

captive_portal:

dashboard_import:
  package_import_url: github://nicholas-ochoa/esphome/sonoff-s31-base.yaml@main
  import_full_config: false

# Device Specific Config

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "status"

sensor:
  - platform: wifi_signal
    name: "wifi_signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "current"
      accuracy_decimals: 1
    voltage:
      name: "voltage"
      accuracy_decimals: 1
    power:
      name: "power"
      accuracy_decimals: 1
      id: power
  - platform: integration
    name: "energy"
    sensor: power
    time_unit: h
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001

time:
  - platform: sntp
    id: the_time

switch:
  - platform: gpio
    name: "relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin: GPIO13
